name: Louder Than Words
favicon: null
layout_spectrum: 0
typography_spectrum: 0.13842
title: Automotive Literary Solipsism.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#505050'
    - '#767676'
    - '#151515'
    - '#dbdbdb'
    - '#b3b3b3'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
