name: Louder Than Words
favicon: null
layout_spectrum: 0.00179
typography_spectrum: 0.13842
title: Automotive Literary Solipsism.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#452c18'
    - '#000000'
    - '#9c743c'
    - '#74532a'
    - '#c69851'
  brandStrength: 1
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
