name: Louder Than Words
favicon: null
layout_spectrum: 0.29654
typography_spectrum: 0.91527
title: Automotive Literary Solipsism.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4edca'
    - '#44293c'
    - '#c06c47'
    - '#b2a293'
    - '#a1212d'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
