name: Louder Than Words
favicon: null
layout_spectrum: 0.01014
typography_spectrum: 0.91527
title: Automotive Literary Solipsism.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#3e4f59'
    - '#627582'
    - '#8ea8b4'
    - '#f4fcfe'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
