typography_spectrum: 0.13842
color:
  brandColors:
    - '#452c18'
    - '#000000'
    - '#9c743c'
    - '#74532a'
    - '#c69851'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Louder Than Words
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: AUTOMOTIVE LITERARY SOLIPSISM.
description: AUTOMOTIVE LITERARY SOLIPSISM.
purpose: []
