name: Louder Than Words
favicon: null
layout_spectrum: 0.90632
typography_spectrum: 0.49165
title: 'Louder Than Words '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#110d0a'
    - '#c7c9c4'
    - '#938f8e'
    - '#c34f50'
  brandStrength: 0.979682378936559
  lightness: 0.8224218329414725
  saturation: 0.3211658103391528
  rhythmicContrast: 0.5
purpose: []
