name: Louder Than Words
favicon: null
layout_spectrum: 0.01014
typography_spectrum: 0.49165
title: Automotive Literary Solipsism.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e7ea'
    - '#122733'
    - '#68727c'
    - '#a5000c'
    - '#fe2830'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
